### ISSUE TITLE
Minified badges too large

### ISSUE THREAD

**Issue by javanilla** [Durss/Twitchat#10]
When the text size is set to a value of 4 or higher, the minified badges are larger than the regular badges.
Plus I've noted in my case that I have 2 badges in the chat (broadcaster + verified), and when I activate the minified badges I have 3 badges, 1 purple (sub badge I presume) + 1 red (broadcaster) + 1 purple with a white dash (verified).

**Comment by Durss** [comment]
Hello Javanilla, thank you for that feedback.
The badges actually scale with the text size but i realized the normal badges weren't wich wasn't normal.
Witht he next release they will scale up with the text. The minified versions will then be smaller.
I also slightly reduced the minified badges and removed the sub badge for the broadcaster.
