### ISSUE TITLE
Show outbound whispers in chat

### ISSUE THREAD

**Issue by viddie** [Durss/Twitchat#25]
Inbound whispers can already be shown in chat:
![image](https://user-images.githubusercontent.com/11546103/191209693-289898ff-87d5-4934-8b2f-4eb8231ab48e.png)

However, outbound whispers, e.g. the "/w <name> <message>" command, aren't shown in chat.
I personally whisper to viewers a bunch and while it does work, some feedback in chat would be good since I'm sometimes not sure whether I messaged the correct person.

**Comment by Durss** [comment]
That's done :)
