### ISSUE TITLE
Add 3rd party emotes to emote autofill suggestions

### ISSUE THREAD

**Issue by viddie** [Durss/Twitchat#28]
Twitch global and sub emotes are already in the emote autofill feature when typing ":<emote-prefix>" in chat:
![image](https://user-images.githubusercontent.com/11546103/195045216-229ba455-21d7-40d8-a74e-015203a37ff4.png)

It would be awesome if 3rd party emotes could also be quickly found with the autofill feature, e.g. typing "pp" would also show 7TV's ppL in the suggestions.

**Comment by Durss** [comment]
It's done but will only be available in weeks (month.?) when the new version is ready.
