### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by shikaruko** [Durss/Twitchat#29]
Hello,

I don't know if the issue come from twitch or twitchat, but i've a error 400 when i try to authorize the link between both.I've already do an authorize few week ago without issue to test and cancel it until a new try

Thanks you for the tool

**Comment by Durss** [comment]
Hello @shikaruko !

Can you detail every step leading to the issue so I better understand where the error might comre from?

Someone told be he had a wrong auth redirection some hours ago, leading to a 404 twitch page, but from what i've seen it was an issue on twitch side. Maybe it's linked to your issue.

**Comment by shikaruko** [comment]
I click on log in with twitch on twitchat main page. I've access to a page on id.twitch.tv that show me all the permission i'll allowed. And after a click on Authorize, i've a redirection to https://id.twitch.tv/oauth2/authorize that lead to a 404 twitch page.

**Comment by Durss** [comment]
Ok so you have the exact same problem as the other person.

Is there an apostrophe `'` at the end of the URL when you are on the 404 page ?

**Comment by shikaruko** [comment]
I've this 
![erreur twitchat](https://user-images.githubusercontent.com/13643289/199364250-e11112bb-eda8-4bd8-b716-150d9d6937fa.png)

**Comment by Durss** [comment]
Can you confirm that you have `response_type=code` on the URL before that ? _(the one with 803 chars)_
You're not redirected to `https://id.twitch.tv/oauth2/'` after the one on your screen ?

**Comment by shikaruko** [comment]
I've response_type=code on the url with 803 chars

**Comment by Durss** [comment]
Thanks for the info.
To me it's an issue on twitch side as I've changed nothing of the login process for months and deployed no Twitchat update for weeks so there no reason it would fail now when it's been working perfect for months.

Let me know if you're still experiencing the issue in the coming days.
I'll let you know if I have news about it :)

**Comment by Durss** [comment]
Other apps appear to have the same issue, I think it's safe to say it's an issue on Twitch side.
I guess it should be fixed pretty "soon".

**Comment by Durss** [comment]
Confirmed by Twitch, it should be fixed now :)
