### ISSUE TITLE
Unable to access OBS remotely

### ISSUE THREAD

**Issue by Macharius92** [Durss/Twitchat#31]
Hi there,

It seems like any other IP than the loopback ends with an attempt to open the OBS websocket over a secure channel (on wss://) resulting in not being able to control OBS from another computer on a local network (as it seems that OBS doesn't offer the ability to set a secure WebSocket). Would it be possible to offer the opportunity to make the secure access an opt-in option instead of a default behaviour ?

**Comment by Durss** [comment]
Hello!
I indeed force a secured connection attempt if using any IP other than 127.0.0.1.
I could disable that logic and simply connect in an unsecured way no matter the IP but the browser would block the connection.
Browsers do not allow calling unsecured protocols from secured ones.
AFAIK, the only solution to control a remote OBS instance is to use SSL tuneling via Ngrok or any other alternative, unless OBS-websocket supports secured connexion but they told me it won't happen _(or at least it's not planned yet)_
