### ISSUE TITLE
Unable to use the obs integration 

### ISSUE THREAD

**Issue by monani614** [Durss/Twitchat#45]
Hello I have obs 28.1.2 with integrated websocket but when I try to link twitchat to obs (to cut stream after raid) it says I need obs28+ OR websocket 5 when I try to install WS5 it doesn't work and says the plugin can't be loaded
Is it normal ?

**Comment by Durss** [comment]
Hello!
You should not install obs-ws 5 if you have obs 28.
It may actually corrupt the pre installed plugin.

What problem do you have exactly? Did you set the proper credentials on the connection form? Does it shows a specific error?

**Comment by monani614** [comment]
I tried without any websocket installed and it doesn't work either
I restarted my pc and also logged out and relogged in but is doesn't change anything
I did not touch to the ip address but as i run obs28+ i don't have any ws password

**Comment by Durss** [comment]
You can also see a password on obs28. The plugin is pre installed but you can still configure it.
Also you need to enable it first so you can use it. Have you done that?

**Comment by monani614** [comment]
Where do I set the pw? there is no ws in tools or any settings

**Comment by monani614** [comment]
i reinstalled obs it works now

**Comment by Durss** [comment]
Perfect !
Many people have the same issues when upgrading to OBS28, it seems they didn't handle this super cleanly :/
I close this now that it's solved :)
