### ISSUE TITLE
Petit soucis avec les triggers

### ISSUE THREAD

**Issue by Yann0ck** [Durss/Twitchat#57]
Hello et bonjour !

Tout d'abord, un énorme GG pour cet outil incroyable ! du super taff, ultra pratique avec des fonctionnalités vraiment top !

Je me permet ce message ici car je ne sais ou le mettre d'autre.
J'ai un petit soucis avec les triggers : 
J'ai un trigger sur une commande chat ( !kick )
J'ai 2 actions qui s'enchainent de contrôle d'OBS
La première, rendre une source active, cette source est un fichier media
J'ai activer l'option "attendre la fin du media"
La seconde, rendre une source inactive, cette même source

Sur ma scène principale gaming, c'est nickel. Sur toutes les autres, le trigger ne se déclenche pas.
Il a eu marché c'est sur (mes modos m'ont suffisamment fait sursauté avec ce son), mais depuis 3/4 semaines environ j'ai ce comportement. Je ne comprends pas. J'ai refait mes sources, refait le trigger, rien n'y fait. La source est bien sur présente sur toutes les scènes. J'ai même essayer d'imbriquer une scène dans une scène.
Si jamais vous avez une piste pour m'aiguiller ...

Autre chose, sur les triggers toujours, on a la possibilité de faire une condition, c'est top. Mais serait il possible de pouvoir imbriquer plusieurs conditions ? (en gros pouvoir remettre une condition sur le faux ^^ )
Je m'explique, toujours sur ma commande !kick, je souhaiterais que si c'est tel modo cela controle telle source (modo 1 source 1, modo 2 source 2 etc)

Encore une fois merci pour ce fabuleux outil !

**Comment by Durss** [comment]
Hello :)

Si jamais il y a un discord sur lequel l'essentiel des retours/suggestions sont centralisés :
https://discord.gg/fmqD2xUYvP

Merci pour ce retour !
Est-ce que la source en question est inclue de la même manière sur ta source gaming que sur les autres ?
Est-ce que tu peux faire un `/triggerlogs` pour voir ce que les logs d'exécution disent ? Théoriquement s'il y a une erreur ou autre c'est censé y remonter. Chaque ligne et sous ligne peut être déroulée pour voir les détails

Concernant les conditions c'est un peu tricky. L'idéal ce serait en réalité d'avoir une condition par action de trigger mais ça serait très lourd à la fois à mettre en place, à utiliser, et à exécuter donc j'ai préféré miser sur une condition globale.
L'idée de pouvoir créer plusieurs conditions _(au lieu de juste les 2 actuelles)_ serait pas mal mais un peu tricky à mettre en place. Je garde ça dans un coin de la tête si jamais j'ai une illumination pour gérer ça facilement mais n'attends rien à ce niveau pour ne pas être déçu :D

Actuellement ton besoin n'a qu'une solution je pense, créer plusieurs fois le même trigger avec une condition différente par modo.
Une autre option aurait pu être qu'au lieu de choisir une source OBS depuis la liste déroulante on puisse avoir un champ texte libre dans lequel on puisse utiliser les placeholder.
Ca te permettrait par exemple de choisir une source OBS dynamiquement.
Au lieu d'avoir des sources genre `"Kick1"` `"Kick2"` `"Kick3"` tu pourrais avoir des sources `"Kick_pseudoModo1"` `"Kick_pseudoModo2"` et `"Kick_pseudoModo3"`, et en mettant comme nom de source  `"Kick_{LOGIN}"` ça ferait ce que tu veux. Ca ouvrirait plus de possibilité que des conditions qu'il faudrait démultiplier pour arriver au même résultat.

Je garde aussi ça dans un coin de tête mais avec plus de chances que ça puisse arriver :)

**Comment by Durss** [comment]
Hello @Yann0ck !
Est-ce que tu as du neuf à ce sujet ?

J'ai fait des tests de mon côté et tout semble bon.
Il y a un cas où ça peut ne pas faire ce que tu attends, c'est si la source est présente plusieurs fois dans une scène, seule l'une d'entre elles sera contrôlée. Si celle qui est contrôlée est masquée par une autre source au-dessus d'elle ou hors champs tu peux ne pas voir qu'elle est bien affichée/masquée par twitchat.
Peut-être est-ce ton cas ?

L'idéal si tu as besoin que des éléments soient sur toutes tes scènes c'est de les mettre dans une scène puis d'inclure cette scène partout, je ne sais pas si c'est ce que tu fais ?

Dans le cas contraire je suis preneur des réponses aux-questions de mon message précédent quand tu as un peu temps.

**Comment by Yann0ck** [comment]
Hello !

J’ai ete pas ma occupé avec le boulot
J’ai rester plusieurs fois et la bizarrerie c’est que la scene ou le son se
declanche varie … genre lors de mon dernier stream c’est ma scène de
discussion qui était active

J’ai prévu de refaire entièrement mes scènes OBS en faisant justement des
imbrications de scènes (qui sera plus simple à gérer que ce que j’ai
actuellement)

La je suis en weekend avec ma chérie donc j’ai pas possibilité de tester
des trucs

La semaine prochaine je vais avoir un peu plus de temps donc je pourrais te
faire un retour.

Y’a que cette partie que je capte pas trop :
« Si celle qui est contrôlée est masquée par une autre source au-dessus
d'elle ou hors champs tu peux ne pas voir qu'elle est bien affichée/masquée
par twitchat »
Admettons j’ai 3 sources médias pilotées par 3 commandes. Il faut donc
qu’elles soient au dessus du reste c’est ca ?
J’ai pas vérifié ce point

Je reviens vers toi au plus vite


Le mer. 11 oct. 2023 à 18:05, François Dursus ***@***.***> a
écrit :

**Comment by Durss** [comment]
Hello !

Quelqu'un a eu un souci d'apparence assez différente mais qui à priori avait exactement la même racine que la tienne.
J'ai déployé un correctif il y a de très grandes chances que ça règle ton problème aussi :)

Pour la faire très courte il est très probable que quand tu ne voyais rien se produire c'est simplement que twitchat contrôlait bien la bonne source mais dans la mauvaise scène à cause d'une logique de mise en cache un peu bancale.

Je te laisse me dire si c'est mieux dés que tu en as la possibilité :)

Bon weekend !

**Comment by Yann0ck** [comment]
Et yoooo !
Alors après mon stream de Lundi, tout refonctionne comme prévu !!!
Le correctif a résolu mon soucis ^^
Trop bien !
A mon prochain twitch payout, une partie ira pour toi ;)

Le sam. 14 oct. 2023 à 18:45, François Dursus ***@***.***> a
écrit :

**Comment by Durss** [comment]
Parfait je ferme cette issue alors :)
N'hésite pas si tu rencontres d'autres soucis!
