### ISSUE TITLE
Under linux, freetype source not recognized as text for trigger

### ISSUE THREAD

**Issue by kuon** [Durss/Twitchat#59]
I am trying to create a trigger that update the text of an OBS source, the source is a text source under linux but in the "Action" menu, I do not have the option to update the text.

If I use `obs-websocket-js` and list the items, my note item is as follow:

```
    {
      inputKind: 'text_ft2_source_v2',
      isGroup: null,
      sceneItemBlendMode: 'OBS_BLEND_NORMAL',
      sceneItemEnabled: true,
      sceneItemId: 40,
      sceneItemIndex: 14,
      sceneItemLocked: false,
      sceneItemTransform: [Object],
      sourceName: 'Note Text',
      sourceType: 'OBS_SOURCE_TYPE_INPUT'
    },
```

If I do the following call, it updates the source properly:

```
return obs.call("SetInputSettings", { inputName: "Note Text", inputSettings: { text: "Hello World" } }); 

```

**Comment by kuon** [comment]
I think the fix is simply change this:

https://github.com/Durss/Twitchat/blob/26fd2ab854e4b5b1ded08fd9718bc764007cedac/src_front/components/params/contents/triggers/entries/TriggerActionOBSEntry.vue#L114

And check that `inputKind` starts with `text_` instead of comparing exactly with the type (there is also a `pango` text type under linux).

**Comment by Durss** [comment]
Good catch!
I only tested on windows and found no clear documentation about possible input types on different platforms so I'm not suprised there's an issue with this !

I'll fix that thanks !

**Comment by Durss** [comment]
Should be fixed :)
Please reopen if you still have the issue !

**Comment by Durss** [comment]
Should be fixed :)
Please reopen if you still have the issue !
