### ISSUE TITLE
Add a enable toggle button on trigger page

### ISSUE THREAD

**Issue by kuon** [Durss/Twitchat#63]
On the trigger edition page, there are 4 buttons:

- Resync rewards
- Resync twitch extensions
- Test trigger
- Delete trigger

I suggest you add a toggle control to enable/disable the trigger from this page.

The use case is this: when I create a trigger "on the fly", for example "on any message", in a chat that is busy, I want to be able to test it by enabling it for like 5 seconds then turning it off, and this would be easier from the trigger page. Having to go back, find the trigger in the list, toggle it... is a bit of a usability problem.

**Comment by Durss** [comment]
I just added that !
![image](https://github.com/Durss/Twitchat/assets/721001/198f696f-d113-48d8-a70c-2901606809d4)
