### ISSUE TITLE
Add .editorconfig

### ISSUE THREAD

**Issue by kuon** [Durss/Twitchat#66]
I started opening files in the project, and my editor is messing with the code automatically, especially it is triming trailing whitespace and ensuring newline at end of file, also it replaces tabs with spaces.

I suggest you add an `.editorconfig` file to the project to help with this.

I usually use `trim_trailing_whitespace` and `insert_final_newline` to both `true`, but you might set them to your liking, having the `.editorconfig` ensure editors of contributing developers will follow your style.

https://editorconfig.org/#supported-properties

**Comment by Durss** [comment]
Didn't know about this thank you 🙏
Added on main branch

**Comment by kuon** [comment]
I saw the file you added, good. Just as a side note, ensure you have an `.editorconfig` plugin enabled in your editor, to be sure your own editor is following it.

Cheers!

**Comment by Durss** [comment]
Yep I added it to generate the file :D
