### ISSUE TITLE
Viewer count icon not showing

### ISSUE THREAD

**Issue by kuon** [Durss/Twitchat#67]
The viewer count icon is not showing properly:

![image](https://github.com/Durss/Twitchat/assets/160200/1d789da5-9f28-4437-99ed-a58086207f23)

There seem to be an issue with the SVG URL escaping:

![image](https://github.com/Durss/Twitchat/assets/160200/2cbbdc8a-648a-4dc8-adb8-389b1a0d8ad0)

It seems the SVG is not encoded properly with `encodeURIComponent`.

**Comment by Durss** [comment]
That's on firefox right ?
I saw that a few days ago (only on firefox for me) and forgot about it.
I just fixed it on main branch :)

**Comment by kuon** [comment]
Yes it's under firefox, but not escaping data URL is non standard and it's "lucky" that chrome handle it.

**Comment by Durss** [comment]
Yes, the thing is I actually thought the builder would add the URL of the file instead of inlining it.
That's why I didn't think about escaping anything.

I'd actually should find out if there's a way to avoid the builder from inlining SVGs instead of my escaping patch, but for now that'll do!
