### ISSUE TITLE
Start/Stop OBS stream depuis chat

### ISSUE THREAD

**Issue by sylverr** [Durss/Twitchat#71]
Bonjour !
Serais-ce possible de mettre en place des commandes pour démarrer et arrêter un stream OBS depuis le chat ? Personnellement on utilise le PC pour restreamer sur twitch et ca nous éviterais de passer par un teamviewer ou autre prise en main à distance.
Bien entendu sans doute avec des droits plus durs que les autres commandes du genre uniquement broadcaster ou liste spécifique de personnes !

Merci pour le travail déjà énorme ! :)

**Comment by Durss** [comment]
Hello !
J'ai dans les cartons depuis un moment de refondre l'action de trigger de contrôle OBS pour permettre d'exécuter d'autres types d'actions OBS, dont le lancement et la coupure de stream.

Si besoin il y a déjà une commande non documentée pour couper le stream, mais pas pour le lancer:
`/__stopobsstream__`

Tu peux utiliser ça depuis les triggers.
Si tu créé un trigger de commande de tchat il te suffit d'utiliser l'action "envoyer un message" et d'y écrire la commande en question:
![image](https://github.com/Durss/Twitchat/assets/721001/8b00945a-3dbd-438a-8494-e1983d33152f)

Si tu ne trouve pas les triggers clique l'épingle en haut du menu de paramètres:
![image](https://github.com/Durss/Twitchat/assets/721001/e33be962-4b9e-40eb-9235-27adc83cfe15)

**Comment by sylverr** [comment]
Ravi d'apprendre que c'est dans la todo list !
Merci aussi pour la commande de stop, ca va nous être déjà bien utile :)

**Comment by Durss** [comment]
Prochaine version il y aura des actions dédiées :)
![image](https://github.com/user-attachments/assets/250e44e1-9de0-4214-86cd-cd9d5d51ee3f)

**Comment by sylverr** [comment]
Trop cool ! Merci 😊
