### ISSUE TITLE
Ajout d'une connexion avec tiktok ?

### ISSUE THREAD

**Issue by Drilmo** [Durss/Twitchat#78]
Je sais que twitchchat indique clairement twitch mais dans les faits, la plupart des streamer d'aujourd'hui doivent tenter de passer par des streams via tiktok pour avoir de la visibilité.

Penses tu pouvoir ajouter une prise en compte d'une connexion avec tiktok (chat et event) ?

Merci d'avance pour ton retour 😄

**Comment by Durss** [comment]
Malheureusement TikTok n'a aucune API ouverte.
A moins d'avoir un contact interne il n'est pas possible d'avoir accès à leur API (et encore j'suis même pas certain qu'il existe une telle API)

Il est "techniquement" possible de se conecter à un ychat tiktok mais ça repose sur un hack qui peut être coupé par tiktok à tout moment et nécessiter de contourner à nouveau leurs protectections. C'es tpas vraiment viable donc.
De plus, à moins de faire une version installable de Twitchat, la solution actuelle pour se connecter à TikTok induirait une très grosse charge pour mon serveur qui n'est pas du tout dimensionné pour ça. Ce qui induirait du coup pas mal de frais supplémentaires.

A défaut, moyennant un peu de dev, il est techniquement possible d'avoir un serveur qui tourne chez vous et qui envoie les messages dans twitchat [grâce à son API ](https://github.com/Durss/Twitchat/blob/main/PUBLIC_API.md#custom_chat_message).

Si jamais tu as les connaissances nécessaires tu peux utiliser la lib [TikTokLive](https://github.com/isaackogan/TikTokLive/) qui est vraiment bien fichue.

**Comment by Drilmo** [comment]
> Malheureusement TikTok n'a aucune API ouverte. A moins d'avoir un contact interne il n'est pas possible d'avoir accès à leur API (et encore j'suis même pas certain qu'il existe une telle API)
> 
> Il est "techniquement" possible de se conecter à un ychat tiktok mais ça repose sur un hack qui peut être coupé par tiktok à tout moment et nécessiter de contourner à nouveau leurs protectections. C'es tpas vraiment viable donc. De plus, à moins de faire une version installable de Twitchat, la solution actuelle pour se connecter à TikTok induirait une très grosse charge pour mon serveur qui n'est pas du tout dimensionné pour ça. Ce qui induirait du coup pas mal de frais supplémentaires.
> 
> A défaut, moyennant un peu de dev, il est techniquement possible d'avoir un serveur qui tourne chez vous et qui envoie les messages dans twitchat [grâce à son API ](https://github.com/Durss/Twitchat/blob/main/PUBLIC_API.md#custom_chat_message).
> 
> Si jamais tu as les connaissances nécessaires tu peux utiliser la lib [TikTokLive](https://github.com/isaackogan/TikTokLive/) qui est vraiment bien fichue.

Ho ok je comprend effectivement, je vais voir pour me faire ca en js 😄

**Comment by Durss** [comment]
je ferme vu que ça arrive ;)
