### ISSUE TITLE
Scrollbar not working on Firefox

### ISSUE THREAD

**Issue by javanilla** [Durss/Twitchat#8]
Tried in differents tabs, works fine with Chrome but the scrollbar seems to be locked in Firefox when using the mouse. Using the Stream Deck plugin, I managed to scroll it up and down, but still not with the mouse even after that.

Windows 10 64-bit 21H2, Firefox 100.0

**Comment by Durss** [comment]
Good catch thank you that made learn something quite important for my future devs !
Will be fixed in the next release!
