### ISSUE TITLE
Autoscroll when changing font size

### ISSUE THREAD

**Issue by javanilla** [Durss/Twitchat#9]
Tried this on Firefox and Chrome, same thing happened.
When the text size is set to a small value (let's say up to 3-4) and there's already a lot of messages in the chat, changing the text size for a higher value triggers an autoscroll of the chat that can't be stopped. The more messages, the more it takes for the scroll to complete and scroll down until the most recent message.

**Comment by Durss** [comment]
Will be fixed in the next release thank you :)
